### ISSUE TITLE
Clip reranking

### ISSUE THREAD

**Issue by adnan11111111** [openai/CLIP#102]
I try to use CLIP for ranking the image that produce by DALLE model 
I must install **!pip install git+https://github.com/openai/CLIP.git**  but it require torch = 1.7.1 
and this version of torch haven't **torchtext = 0.9.1** 
when I use torch = 1.7.1 I have this error :
![image_2021-05-04_235210](https://user-images.githubusercontent.com/45887021/117068275-bfef4b00-ad33-11eb-8ca3-f491c4667830.png)

when I use torch = 1.8.1 I have this error :
**'CLIP' object has no attribute 'load'**
what should I do ,Please?

**Comment by jongwook** [comment]
It's likely from a version discrepancy where torchtext was compiled with a newer version of pytorch but installing CLIP downgraded pytorch to 1.7.1. Until we fix the dependency issue, try [this trick](https://github.com/openai/CLIP/issues/106#issuecomment-846085583) to ignore CLIP's dependencies.
