### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement torchvision~=0.8.2 (from clip) ERROR: No matching distribution found for torchvision~=0.8.2

### ISSUE THREAD

**Issue by Ycta** [openai/CLIP#105]
ERROR: Could not find a version that satisfies the requirement torchvision~=0.8.2 (from clip)
ERROR: No matching distribution found for torchvision~=0.8.2

Got that despite installing

**Comment by jongwook** [comment]
We're aware of the version discrepancy and plan to ease the requirements. Try [this trick](https://github.com/openai/CLIP/issues/106#issuecomment-846085583) in the meanwhile.

**Comment by jongwook** [comment]
Should be fixed now by db20393f4affd4158528bd868478e516ebed0944
