### ISSUE TITLE
Use pretrained CLIP with a context_length not equal to 77 (default value)

### ISSUE THREAD

**Issue by ABaldrati** [openai/CLIP#110]
Thanks you guys for the amazing job and releasing CLIP model.

As written in the title I wanted to ask if it was possible to use pretrained CLIP models with a context_length different from the default value (which is 77).

If I try to change the `context_length` of the tokenizer to another value (like 150), using pretrained clip model "out of the box" I get the following error:
`File "/homes/students_home/abaldrati/miniconda3/lib/python3.8/site-packages/clip/model.py", line 342, in encode_text
    x = x + self.positional_embedding.type(self.dtype)
RuntimeError: The size of tensor a (150) must match the size of tensor b (77) at non-singleton dimension 1`

Thanks again for the amazing work

**Comment by vinson2233** [comment]
I don't think that's possible since the network is designed and trained for context_length up to 77.  
You might want to retrain your model from scratch, or just reduce your text so it <= 77 characters

**Comment by ABaldrati** [comment]
Yes I imagined that, thanks for the answer anyway

**Comment by iasonasxrist** [comment]
Same problem! Suppose i cannot edit it due to the training  process
