### ISSUE TITLE
what text you use in (image, text) pairs

### ISSUE THREAD

**Issue by CastleCC** [openai/CLIP#118]
Thanks for this amazing work.

This is a question related to the paper, In paper section 8,  "CLIP only uses full text sequences co-occuring with images as supervision rather than just the queries".  I am curious what “full text sequences” refer to,  the image google title or the webpage text along with the image, or other text.

**Comment by jongwook** [comment]
The dataset is a mixture of image-text pairs from various sources. The "full text sequences" are usually title + description concatenated using whatever is available about the image, usually being a sentence or two and not the whole webpage. Similar work from google [(ALIGN)](https://ai.googleblog.com/2021/05/align-scaling-up-visual-and-vision.html) uses alt texts.
