### ISSUE TITLE
training clip 

### ISSUE THREAD

**Issue by LilyTheBear** [openai/CLIP#119]
Hi, 
would you mind to explain the size, dimension and the format of input sensors for training ? or provide an example ?

best

Niloo

**Comment by vinson2233** [comment]
Have you seen this thread? https://github.com/openai/CLIP/issues/83
Image is PIL format, it can be in any size, the `preprocess` object from CLIP will handle the resize. If your image composed in 4 change (RGBA), put `.convert('RGB')` after PIL image reading.

The text is just list of string. The ideal size is <= 77 characters.

**Comment by jongwook** [comment]
@vinson2233 's example in #83 basically does it (thank you!).

Some details: grayscale (1 channel) or RGBA (4 channels) images are converted to 3-channel RGB images by the CLIP preprocessor ([this line](https://github.com/openai/CLIP/blob/main/clip/clip.py#L62)). The tokenizer will produce about 1-3 tokens from each word, so 77 tokens is often lot longer than 77 characters.

**Comment by vinson2233** [comment]
@jongwook i see, thanks for the explanation.

**Comment by MonolithFoundation** [comment]
@jongwook hi, how to do this in hf's CLIPImageProcessor?

https://github.com/openai/CLIP/blob/dcba3cb2e2827b402d2701e7e1c7d9fed8a20ef1/clip/clip.py#L76
