### ISSUE TITLE
pip install git+https://github.com/openai/CLIP.git     doesn't work

### ISSUE THREAD

**Issue by Tatm24** [openai/CLIP#123]
when I type "pip install git+https://github.com/openai/CLIP.git"  it gives me this error message:

(StyleCLIP) C:\Users\tatm2>pip install git+https://github.com/openai/CLIP.git
Collecting git+https://github.com/openai/CLIP.git
  Cloning https://github.com/openai/CLIP.git to c:\users\tatm2\appdata\local\temp\pip-req-build-y3_zwrrr
  Running command git clone -q https://github.com/openai/CLIP.git 'C:\Users\tatm2\AppData\Local\Temp\pip-req-build-y3_zwrrr'
  ERROR: Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/openai/CLIP.git 'C:\Users\tatm2\AppData\Local\Temp\pip-req-build-y3_zwrrr'
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

Please help, I don't do things like this very much.

**Comment by vinson2233** [comment]
The error is literally saying"ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?".
1. Have you install git in your system?
2. If the answer is yes, does the git included in your PATH environment variables?
