### ISSUE TITLE
Updating `clip-by-openai` PyPi package

### ISSUE THREAD

**Issue by r-mirchandani** [openai/CLIP#141]
Hello! As an avid user of this package, just wanted to see if there were any plans to release an updated version of the PyPi package for CLIP? It seems like the last release was at the end of January, and a lot of QoL tweaks have been added to the repo since then - compatibility with new versions of PyTorch, for example.

Thanks in advance, and for making this work so open for the community to take advantage of!

**Comment by jongwook** [comment]
Hi, the PyPI package is not maintained by us, but someone with username "jacky2wong".

Our recommended method to install the Python package at the moment is this:

```
pip install git+https://github.com/openai/CLIP.git
```
