### ISSUE TITLE
how to use clip on chinese dataset?

### ISSUE THREAD

**Issue by minmummax** [openai/CLIP#142]
I want to use clip on my Chinese dataset, how to pretrain this model?

**Comment by jongwook** [comment]
See #7 and https://github.com/FreddeFrallan/Multilingual-CLIP

**Comment by yangapku** [comment]
Hi, maybe you can refer to this repo! https://github.com/OFA-Sys/Chinese-CLIP

**Comment by troilus-canva** [comment]
> Hi, maybe you can refer to this repo! https://github.com/OFA-Sys/Chinese-CLIP

🤔 it seems not available anymore

**Comment by yangapku** [comment]
> > Hi, maybe you can refer to this repo! https://github.com/OFA-Sys/Chinese-CLIP
> 
> 🤔 it seems not available anymore

I'm sorry our main repo must be closed now due to some unavoidable reasons 😢 . However, forks of our repos in the Github community still exist, like https://github.com/billjie1/Chinese-CLIP. You can still have a try.

**Comment by yangapku** [comment]
@troilus-canva Hi, our main repo is reopened again! We have added more model scales, technique report and retrieval demo. Please checkout https://github.com/OFA-Sys/Chinese-CLIP for our latest update.
