### ISSUE TITLE
Availability of Rendered SST2 and Country211 datasets

### ISSUE THREAD

**Issue by pj-ms** [openai/CLIP#154]
Hi,
Thanks for the great work! In the paper, it mentions "we created two datasets that we call **Country211** and **Rendered SST2**. The Country211 dataset is designed to assess the geolocation capability of visual representations. We filtered the YFCC100m dataset (Thomee et al., 2016) to find 211 countries (defined as having an ISO-3166 country code) that have at least 300 photos with GPS coordinates, and we built a balanced dataset with 211 categories, by sampling 200 photos for training and 100 photos for testing, for each country"

I wonder if it is possible to share those two datasets for reproducibility purpose? Thanks!

**Comment by Ascn89** [comment]
Hi,
i would also be interested in these datasets. Especially Country211 as i find this type of problem really interesting.
Thanks!

**Comment by jongwook** [comment]
Added in efe8cbbdf3e594999706558de021de55e04cab5f !

**Comment by pj-ms** [comment]
@jongwook  Thanks for adding them!

**Comment by pj-ms** [comment]
Hi, @jongwook, btw, in CLIP paper, the number of training images is listed as 43200, which is probably a typo, as 200 * 211 = 42200.

![image](https://user-images.githubusercontent.com/25910409/134724367-db28666e-1178-43d7-adea-b925c3be39f8.png)
 
 
 
![image](https://user-images.githubusercontent.com/25910409/134724507-7cbd3cd5-c517-4d9b-a916-0d1e58fe16c1.png)
