### ISSUE TITLE
Is there away where CLIP gives use multiple outputs like Multiple Object Detection

### ISSUE THREAD

**Issue by Srkshaikh5** [openai/CLIP#155]
Hi, 

Can You Help me, where If we ask the CLIP irrelevant questions with Image and it still tries to fit the score  even if the class is not there, because of the Softmax layer used.
Or 
Is there away where CLIP gives use multiple outputs like if we ask for multiple objects in the image and it gives score for each object separately like we do in object detection.

**Comment by jongwook** [comment]
See #82 for related discussions.
