### ISSUE TITLE
RuntimeError: Cannot call numpy() on Tensor that requires grad 

### ISSUE THREAD

**Issue by woctezuma** [openai/CLIP#16]
When running the first usage example on a machine without GPU ([on Heroku](https://github.com/woctezuma/heroku-clip)), I have encountered an error message.

This is the usage example:

```python
import torch
import clip
from PIL import Image

device = "cuda" if torch.cuda.is_available() else "cpu"
model, preprocess = clip.load("ViT-B/32", device=device)

image = preprocess(Image.open("CLIP.png")).unsqueeze(0).to(device)
text = clip.tokenize(["a diagram", "a dog", "a cat"]).to(device)

with torch.no_grad():
    image_features = model.encode_image(image)
    text_features = model.encode_text(text)
    
    logits_per_image, logits_per_text = model(image, text)
    probs = logits_per_image.softmax(dim=-1).cpu().numpy()

print("Label probs:", probs)  # prints: [[0.9927937  0.00421068 0.00299572]]
```

This is the error message:

```
RuntimeError: Cannot call numpy() on Tensor that requires grad 
```

I have followed the recommendation displayed along the error message, and changed this line from:

```python
    probs = logits_per_image.softmax(dim=-1).cpu().numpy()
```

to:

```python
    probs = logits_per_image.softmax(dim=-1).cpu().detach().numpy()
```

I have no idea whether the issue is specific to my machine, but I might as well mention it here.

**Comment by jongwook** [comment]
That's strange, since `torch.no_grad()` should have disabled any gradient computation. Although `detach()` did the trick for you, there's a chance that your code is using unnecessary memory/compute to retain gradient information.

Could you double-check if the `numpy()` line is under the `with torch.no_grad():` block, and if it's the case (and if you're comfortable doing this) could you paste the output of the following script:

```
curl -s https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py | python
```

to get the version information of your system and relevant libraries?

**Comment by woctezuma** [comment]
> Could you double-check if the `numpy()` line is under the `with torch.no_grad():` block

You are right. I did not write the `.numpy()` call under the `with torch.no_grad()` block [in my file](https://github.com/woctezuma/heroku-clip/blob/main/app/app.py). Sorry, my bad!

```python
    with torch.no_grad():
        image_features = model.encode_image(image)
        text_features = model.encode_text(text)
    
    logits_per_image, logits_per_text = model(image, text)
    probs = logits_per_image.softmax(dim=-1).cpu().detach().numpy()
```
