### ISSUE TITLE
Get different image_features in different environment?

### ISSUE THREAD

**Issue by MagicCodess** [openai/CLIP#172]
`import torch
import clip
from PIL import Image

device = "cuda" if torch.cuda.is_available() else "cpu"
model, preprocess = clip.load("ViT-B/32", device=device)

image = preprocess(Image.open("CLIP.png")).unsqueeze(0).to(device)
text = clip.tokenize(["a diagram", "a dog", "a cat"]).to(device)

with torch.no_grad():
    image_features = model.encode_image(image)`

This feautures are different in different environment, is there a method to fix it?

**Comment by jongwook** [comment]
Unfortunately there are slight numerical differences depending on which hardware the model was run on. See #114 and #13.
