### ISSUE TITLE
Emoji in Text

### ISSUE THREAD

**Issue by steveguang** [openai/CLIP#174]
Is clip model able to process emoji? or text and images only? I tried to encode two emojis '😀' and '😃'. It generates two embeddings that are different. they are like,
array([[5.50842285e-02, 2.57812500e-01, 4.94384766e-02, .....
array([[ 7.32421875e-02, 3.23242188e-01, 1.26586914e-01,......
Any reason why? It doesnt seem to be random

**Comment by jongwook** [comment]
The BPE encoding supports arbitrary UTF-8 sequence, and it can encode and decode emoji characters accordingly. It'd be interesting project to plot the t-SNE of emoji embeddings.
