### ISSUE TITLE
Could you please release the RN50x64 model?

### ISSUE THREAD

**Issue by GWwangshuo** [openai/CLIP#182]
I am try to using CLIP for large resolution images (e.g., 672x672). However, the pretrained image encoder of CLIP has lower resolution (244x244). How can I use the pretrained image encoder for large resolution images?

Besides, could you please release the pretrained CLIP with image encoder RNx64 since it can handle large resolution (448x448). Thanks a lot.

**Comment by jongwook** [comment]
Fixed in 67fc250eb6aa84ef9ad19a020e3f8eb4e698feb4
