### ISSUE TITLE
Attention is not masked on padding tokens

### ISSUE THREAD

**Issue by mesnico** [openai/CLIP#183]
I noticed that no padding masks are used in the attention computation of the input sentence.
The transformer in the `encode_text` function should be masked with the actual sentence length. However, in this implementation, it appears not to be the case:
https://github.com/openai/CLIP/blob/573315e83f07b53a61ff5098757e8fc885f1703e/clip/model.py#L344 

All the 77 tokens (padding tokens comprised) seem to participate in the attention computation.
Am I missing something?

Thank you in advance!

**Comment by jongwook** [comment]
We use a causal attention mask ([code](https://github.com/openai/CLIP/blob/573315e83f07b53a61ff5098757e8fc885f1703e/clip/model.py#L324-L330), cf. #179) and it basically blocks any information from "future" tokens from flowing back in. So we can take the embedding at the EOT token ([code](https://github.com/openai/CLIP/blob/573315e83f07b53a61ff5098757e8fc885f1703e/clip/model.py#L349-L350)), while safely ignoring any attention calculation of the padding tokens.

**Comment by mesnico** [comment]
I was totally ignoring the pad masking "side effect" of causal attention.
Thank you!

**Comment by andompesta** [comment]
why the same causal masking is applied to the images as well ? I mean images are always sentence of `grid ** 2` length, isn't it ?
