### ISSUE TITLE
Load trained models on torch versions below 1.7

### ISSUE THREAD

**Issue by achalddave** [openai/CLIP#19]
Loading the trained models in pytorch 1.6 leads to errors like the following:

```
aten::_convolution(Tensor input, Tensor weight, Tensor? bias, int[] stride, int[] padding, int[] dilation, bool transposed, int[] output_padding, int groups, bool benchmark, bool de
terministic, bool cudnn_enabled) -> (Tensor):
Expected at most 12 arguments but found 13 positional arguments.
```

Fortunately, it seems like these are largely due to signature changes in pytorch 1.7, and the model does not use pytorch 1.7 specific features. I have written a script to patch these models, in case it is useful for others: https://gist.github.com/achalddave/12e82c3c879589ee287e9c2769c489f0

It would be nice if there were a way to save the models in a way that they work with earlier versions of torch, but I'm not sure if this is possible. Just filing (and closing) this issue in case it is helpful for others who, like me, are working in an environment where upgrading to torch 1.7 is not possible.

**Comment by double-fire-0** [comment]
Can't agree more!
I find a difficult way which may help you to load the model in the lower version pytorch.(for me is 1.5.0)
1. install pytorch 1.7.1 (just cpu version is ok, we only use this pytorch version to get model.state_dict() )
2.Then download the model you want from here:
`"RN50": "https://openaipublic.azureedge.net/clip/models/afeb0e10f9e5a86da6080e35cf09123aca3b358a0c3e3b6c78a7b63bc04b6762/RN50.pt",
    "RN101": "https://openaipublic.azureedge.net/clip/models/8fa8567bab74a42d41c5915025a8e4538c3bdbe8804a470a72f30b0d94fab599/RN101.pt",
    "RN50x4": "https://openaipublic.azureedge.net/clip/models/7e526bd135e493cef0776de27d5f42653e6b4c8bf9e0f653bb11773263205fdd/RN50x4.pt",
    "ViT-B/32": "https://openaipublic.azureedge.net/clip/models/40d365715913c9da98579312b702a82c18be219cc2a73407c4526f58eba950af/ViT-B-32.pt",`

3. Use this code in python or some place to get model
`model = torch.jit.load(model_path, 'cpu')`
4. Use the code `model = model.state_dict()` to get the state dict of the weight
5. Use the code `torch.save(model, 'your_path.pth.tar')` to save the model
6. **Then Back to the pytorch version you want now**
7. Use the build_model method code in model.py to build a model, and edit the code to load the weight which we save at your_path.pth.tar
