### ISSUE TITLE
While using RN50x16, and RN50x64 in VQGAN+CLIP, getting error Unable to find a valid cuDNN algorithm to run convolution

### ISSUE THREAD

**Issue by m-ali-awan** [openai/CLIP#210]
Hi, hope all of you are fine.

I tried to change backends, but it didn't help. Also, trying different Cuda versions didn't help.

Thanks for any help.....!

**Comment by jongwook** [comment]
I can't help on this without detailed steps to reproduce and more information on your environment, and it's probably specific to the code in your notebook out of the scope of this repo. Check out [the issue template from the pytorch repo](https://github.com/pytorch/pytorch/blob/master/.github/ISSUE_TEMPLATE/bug-report.yml) to learn more, and feel free to reopen the issue when you have those info ready.
