### ISSUE TITLE
Modify visual positional embedding to make CLIP independent of input resolution

### ISSUE THREAD

**Issue by ABaldrati** [openai/CLIP#214]
Thank you guys for the awesome work and for releasing CLIP models.

In ResNet models the only component which prevents an arbitrary input resolution is the learned positional embedding in the 2D attention pooling.

I would like to ask if you have performed some experiments with a different approach: for example using a positional encoding which can adapt to a different sequence length or directly removing the positional encoding.

Thanks again for the amazing work

**Comment by jongwook** [comment]
Thanks for the kind words!

We haven't done the specific experiments you described, but I expect replacing the attention pool layer with a simple average pooling, or pooling the attention-pooled features from different crops from the original image, would still work to some degree.

We did bilinear interpolation of the positional encoding vectors when fine-tuning the ViT/L-14 model on 336px which expanded the 16x16 grid to 24x24.
