### ISSUE TITLE
using original transform for high aspect ratio sample 

### ISSUE THREAD

**Issue by jihwanp** [openai/CLIP#215]
Hi, thanks for providing such a fantastic work!
I have a question about the input  transformation for CLIP.
I currently working on zero-shot image classification for custom dataset which i've collect, and it contains a lot of samples which has `high aspect ratio `(i.e, one side is much longer than other side).
I found that the input transformation for CLIP uses resize and crop , and it makes my sample image to be fed into CLIP as only a part of the enitre image.

I wonder is it okay to use `Resize((n_px,n_px),interpolation=...)` instead of `Resize(n_px,interpolation=...)`, so that the input of the model can be more plausible.  Or just zero-padding would be fine?

Thanks

**Comment by jongwook** [comment]
This is one of the limitations of the model. In addition to zero-padding and resizing, you could try pooling multiple square images cropped at different locations, by averaging their features.
