### ISSUE TITLE
How do I train CLIP with my Custom Image Dataset on top of current model ?

### ISSUE THREAD

**Issue by Unmesh28** [openai/CLIP#218]
-  I want to use CLIP for text to art using VQGAN. 
- Planning to provide custom dataset to it [dataset : different painting styles of different artists ]
- If we send a  prompt + style = "A girl playing on the beach" + "Thomas Kinkade" , then it should return art of the prompt in style of Thomas Kinkade.

How do I train such a model on the top of existing one ?

**Comment by jongwook** [comment]
For fine-tuning, you could follow the training tips mentioned in #83, but your mileage may vary depending on the datasets, hyperparameters etc.

Image generation is out of scope of this repo, refer to other CLIP+VQGAN-related resources available on the internet.
