### ISSUE TITLE
clip output is NaN

### ISSUE THREAD

**Issue by chinoll** [openai/CLIP#222]
My CLIP will output NaN when using CUDA, but it will output normally when using CPU. How to solve this problem?
```python
import torch
import clip
from PIL import Image
import numpy as np
device = "cuda:0" #use cuda
model, preprocess = clip.load("ViT-B/32", device=device,jit=False)

text = clip.tokenize(["a photo is comics","a photo is illustration","a photo is empty","a photo is white","a photo is black","a photo is gray","a photo is lineart"]).to(device)
with torch.no_grad():
    image = preprocess(image).unsqueeze(0).to(device)
    logits_per_image, logits_per_text = model(image, text)
    print(logits_per_image)
    probs = logits_per_image.softmax(dim=-1).cpu().numpy()[0]
print(probs)
```
output
```
tensor([[nan, nan, nan, nan, nan, nan, nan]], device='cuda:0',
       dtype=torch.float16)
[nan nan nan nan nan nan nan]
```
CLIP can output the probability normally when using CPU.

**Comment by illtellyoulater** [comment]
same problem here, did you manage to fix it?

**Comment by chinoll** [comment]
> same problem here, did you manage to fix it?

Are you talking about getting the model to produce the correct output? Using model.float() will make the model produce the correct output, but I want to use float16 and the model does not work properly when the input data is in the format float16.

**Comment by illtellyoulater** [comment]
@chinoll yeah I also wanted to make it work with the GPU (and float16)... and I think I've fixed this by using a different version of cuda toolkit. 

Try uninstalling torch & torchvision and then installing them again with `pip3 install torch==1.11.0+cu115 torchvision==0.12.0+cu115 -f https://download.pytorch.org/whl/torch_stable.html`.

If it doesn't work, again uninstall T & TV and reinstall them with `pip install torch==1.10.1+cu102 torchvision==0.11.2+cu102 -f https://download.pytorch.org/whl/torch_stable.html`.

**Comment by SunZhigang7** [comment]
> pip3 install torch==1.11.0+cu115 torchvision==0.12.0+cu115 -f https://download.pytorch.org/whl/torch_stable.html

useful!! thanks

**Comment by chinoll** [comment]
> ```python
> probs = logits_per_image.softmax(dim=-1).cpu().numpy()[0]
> ```

Great!

**Comment by chinoll** [comment]
> @chinoll yeah I also wanted to make it work with the GPU (and float16)... and I think I've fixed this by using a different version of cuda toolkit.
> 
> Try uninstalling torch & torchvision and then install them again with `pip3 install torch==1.11.0+cu115 torchvision==0.12.0+cu115 -f https://download.pytorch.org/whl/torch_stable.html`.
> 
> If it doesn't work, again uninstall them and reinstall them with `pip install torch==1.10.1+cu102 torchvision==0.11.2+cu102 -f https://download.pytorch.org/whl/torch_stable.html`.

Great!
