### ISSUE TITLE
Clip是否由正面人脸的配对训练

### ISSUE THREAD

**Issue by zhou431496** [openai/CLIP#231]
我打算使用clip做人脸正面化重建，请问clip是否可以做到使用"a frontal face"来约束图像生成正面化的人脸。期待你的回复，谢谢

**Comment by jongwook** [comment]
Used Google Translate but not sure if I understood the question correctly. The training data likely contained images containing frontal faces, but we don't have statistics for that. Also your mileages may vary depending on which method and hyperparameters were used for generation.

**Comment by zhou431496** [comment]
thank you for your reply. Can you provide a 128 model and code?

**Comment by zhou431496** [comment]
You can don't understand my problem, if you pass the text of "a Frontal Face", some side images can be changed to a front face. The model we use is STYLECLIP
