### ISSUE TITLE
Encode an image with rscid-v2 and rscid-v2 processor not working

### ISSUE THREAD

**Issue by Pinneaple** [openai/CLIP#232]
Hello,

I would like to encode an image and a text separately into a vector using clip-rscid-v2 and save them into a nearest neighbor library. What will be the best approach to encode an image? I would like to replicate the model.encode_image(image) from the origin clip model. Also, process = CLIPProcessor.from_pretrained("flax-community/clip-rsicd-v2") does not work.

Thanks

**Comment by jongwook** [comment]
This repo is unrelated to HuggingFace's CLIP implementation (`CLIPProcessor`) or independently developed `rscid-v2`. You can find more information or file issue at https://github.com/huggingface/transformers or https://github.com/arampacha/CLIP-rsicd.
