### ISSUE TITLE
How to get BPE vocab given new dataset?

### ISSUE THREAD

**Issue by JunweiLiang** [openai/CLIP#233]
Hi, thanks for the great work!

I'm trying to train model on a new large-scale dataset and would like to use a new BPE dictionaries specific to that dataset. Could you provide some instructions/tools to get the same or similar format as the one in this repo? (like the `bpe_simple_vocab_16e6.txt.gz` file)

Thanks,
Junwei

**Comment by jongwook** [comment]
[Huggingface Tokenizers](https://github.com/huggingface/tokenizers) is best suited for this purpose. Check [their documentations](https://huggingface.co/docs/tokenizers/python/latest/).
