### ISSUE TITLE
CLIP image_encoder as backbone

### ISSUE THREAD

**Issue by iasonasxrist** [openai/CLIP#253]
I have been trying to implement the model.py to separate the image encoder from text but i got plenty of errors kind of :

self.positional_embedding = nn.Parameter(torch.empty(self.context_length, transformer_width))

   raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'CLIP' object has no attribute 'context_length'

Any ideas how to override them?

**Comment by lr19960813** [comment]
> I have been trying to implement the model.py to separate the image encoder from text but i got plenty of errors kind of :
> 
> self.positional_embedding = nn.Parameter(torch.empty(self.context_length, transformer_width))
> 
> raise AttributeError("'{}' object has no attribute '{}'".format( AttributeError: 'CLIP' object has no attribute 'context_length'
> 
> Any ideas how to override them?

Hi, I encountered the same problem as you, how did you solve it, looking forward to your reply. Thanks a lot!
