### ISSUE TITLE
How to train CLIP to  generate embeddings for new image-text pairs?

### ISSUE THREAD

**Issue by smith-co** [openai/CLIP#258]
How to train CLIP to  generate embeddings for new image-text pairs? Can anyone provide me with code snippets or examples?

**Comment by vinson2233** [comment]
https://github.com/openai/CLIP/issues/83

**Comment by smith-co** [comment]
@vinson2233 do you know is there a limit how long the text sequence could be?

**Comment by vinson2233** [comment]
see this issue https://github.com/openai/CLIP/issues/110

**Comment by tengshaofeng** [comment]
this is my training code, everything gose well. https://github.com/tengshaofeng/finetune-jina-clip-v2
