### ISSUE TITLE
Can CLIP apply to video?

### ISSUE THREAD

**Issue by haofanwang** [openai/CLIP#28]
As many details about how you collect the datasets are missed, I would like to know whether it is possible to apply the pretrained CLIP on text-image pairs to retrieve videos (given a text)?

**Comment by jongwook** [comment]
In the eval suite, we used the middle frame of each clip as a lower bound of the performance. At the cost of additional compute, you can also use more (or all) frames and take the average of their features to get a more robust representation of the video clip.

**Comment by dmoham1476** [comment]
Yes tried CLIP with live streaming!

**Comment by AmeerHamza111** [comment]
Can you please share some information on how to train it on live stream or video for that matter. Please

**Comment by Newmu** [comment]
Additionally, Appendix E.3 in the paper describes our experiments on video recognition for some more details.

**Comment by Tortoise17** [comment]
@Newmu  awesome. Can you just share the command line for the video live and recorded usage with clip. it would be kind help.
