### ISSUE TITLE
Question: Is it possible to use the image tensor as float32 without converting it to float16?

### ISSUE THREAD

**Issue by blackbeandu** [openai/CLIP#292]
The title is the content. 

Thank you.

**Comment by Asthestarsfalll** [comment]
[There](https://github.com/openai/CLIP/blob/main/clip/clip.py#L138) you may find the way of converting weights dtype to float32.
Just modify like this:
```python
    if not jit:
        model = build_model(state_dict or model.state_dict()).to(device)
        model.float()
        return model, _transform(model.visual.input_resolution)
``` 
or you can convert it after load model:
```python
clip = load('RN50')
clip.float()
```
Btw, I test the clip with dtype float32, but the acc on ImageNet has a litlle decrease.

**Comment by blackbeandu** [comment]
> [There](https://github.com/openai/CLIP/blob/main/clip/clip.py#L138) you may find the way of converting weights dtype to float32. Just modify like this:
> 
> ```python
>     if not jit:
>         model = build_model(state_dict or model.state_dict()).to(device)
>         model.float()
>         return model, _transform(model.visual.input_resolution)
> ```
> 
> or you can convert it after load model:
> 
> ```python
> clip = load('RN50')
> clip.float()
> ```
> 
> Btw, I test the clip with dtype float32, but the acc on ImageNet has a litlle decrease.

Thanks for the answers @Asthestarsfalll 
I solved it.
