### ISSUE TITLE
BC-breaking pytorch 1.9 vs 1.7.1 in multi_head_attention_forward

### ISSUE THREAD

**Issue by Zhaoyi-Yan** [openai/CLIP#312]
https://github.com/pytorch/pytorch/blob/v1.7.1/torch/nn/functional.py#L4222

https://github.com/pytorch/pytorch/blob/v1.9.0/torch/nn/functional.py#L4836

I cannot find `scaling` in pytorch 1.9, it seems has been removed. So, maybe `First, [install PyTorch 1.7.1](https://pytorch.org/get-started/locally/) (or later) and torchvision` is not correct.

**Comment by jongwook** [comment]
It appears that they refactored the implementation, and the scaling part is now in:

https://github.com/pytorch/pytorch/blob/v1.9.0/torch/nn/functional.py#L4823
