### ISSUE TITLE
Model has been downloaded but the SHA256 checksum does not not match

### ISSUE THREAD

**Issue by Osub** [openai/CLIP#317]
```
Traceback (most recent call last):
  File "/Users/nft/Desktop/work/aphantasia/clip_fft.py", line 319, in <module>
    main()
  File "/Users/nft/Desktop/work/aphantasia/clip_fft.py", line 119, in main
    model_clip, _ = clip.load(a.model, jit=old_torch())
  File "/Users/nft/miniforge3/lib/python3.9/site-packages/clip/clip.py", line 120, in load
    model_path = _download(_MODELS[name], download_root or os.path.expanduser("~/.cache/clip"))
  File "/Users/nft/miniforge3/lib/python3.9/site-packages/clip/clip.py", line 70, in _download
    raise RuntimeError("Model has been downloaded but the SHA256 checksum does not not match")
RuntimeError: Model has been downloaded but the SHA256 checksum does not not match
```

**Comment by jongwook** [comment]
It's likely that an unstable network connection or a firewall have caused an incomplete download. Check if these URLs are accessible manually:

https://github.com/openai/CLIP/blob/3702849800aa56e2223035bccd1c6ef91c704ca8/clip/clip.py#L31-L39

If it was a temporary connection issue, retrying it will probably work.

**Comment by jaded0** [comment]
In my case, the problem is happening repeatedly. I feel like the issue is deeper, because I've never had problems with an unstable connection completely aborting downloads like this.

**Comment by coasxu** [comment]
In my case, when I encountered this error for the first time, I reran the code below again and there was no error.

```
import torch
import clip
from PIL import Image

device = "cuda" if torch.cuda.is_available() else "cpu"
model, preprocess = clip.load("ViT-B/32", device=device)

image = preprocess(Image.open("CLIP.png")).unsqueeze(0).to(device)
text = clip.tokenize(["a diagram", "a dog", "a cat"]).to(device)
```

**Comment by smlynarczyk** [comment]
@jongwook's  suggestion worked for my whisper issue. I had to create the $HOME/.cache/clip directory and then download the ViT.*pt files into it. Thanks @jongwook !
