### ISSUE TITLE
Image feature clustering

### ISSUE THREAD

**Issue by haofanwang** [openai/CLIP#32]
Now, the feature dimension is 512 for both image and text. I'd like to know whether it is possible to do dimension reduction to speed up the inference time. After I do PCA on the image feature, is it possible to use clip features to do clustering?

**Comment by jongwook** [comment]
We don't have data for this. In general, you'll need to find a trade-off point between the dimensionality/speed and feature quality. You might also want to look into [approximate nearest neighbor](http://ann-benchmarks.com/) methods.
