### ISSUE TITLE
Question about image augmentation 

### ISSUE THREAD

**Issue by ZihaoWang-CV** [openai/CLIP#33]
Thanks for your code.

In section2.3 of the paper, it is mentioned that _

> A random square crop from resized images is the only data augmentation used during training

_

What is the resized shape? Is the image first resized to 256x256 and then cropped to 224x224?

Thanks a lot!

**Comment by Newmu** [comment]
It is resized to be at least N pixels in height or width and then cropped to N pixels. So for a training resolution of 224 pixels, the image is first resized to 224 in its minimum dimension and then randomly cropped to a square 224x224.

**Comment by ZihaoWang-CV** [comment]
> It is resized to be at least N pixels in height or width and then cropped to N pixels. So for a training resolution of 224 pixels, the image is first resized to 224 in its minimum dimension and then randomly cropped to a square 224x224.

Thanks for answering!
