### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by minakhan01** [openai/CLIP#35]
How would you like the work to be cited? Thank you so much and thank you for doing such wonderful work! It was a delight to read and use :))

**Comment by Newmu** [comment]
We'll put up and arxiv version sometime once we get another ablation experiment finished I want to include. Fingers crossed I don't get lazy and never do it like what happened for GPT-2...

For now:

@article{radford2021learning,
  title={Learning Transferable Visual Models From Natural Language Supervision},
  author={Radford, Alec and Kim, Jong Wook and Hallacy, Chris and Ramesh, Aditya and Goh, Gabriel and Agarwal, Sandhini, and Sastry, Girish and Askell, Amanda and Mishkin, Pamela and Clark, Jack and Krueger, Gretchen and Sutskever, Ilya},
  year={2021}
}

**Comment by jongwook** [comment]
Now that we have arxiv submission, the citation can be:

```
@article{radford2021clip,
  title={Learning Transferable Visual Models From Natural Language Supervision}, 
  author={Alec Radford and Jong Wook Kim and Chris Hallacy and Aditya Ramesh and Gabriel Goh and Sandhini Agarwal and Girish Sastry and Amanda Askell and Pamela Mishkin and Jack Clark and Gretchen Krueger and Ilya Sutskever},
  journal={arXiv preprint arXiv:2103.00020},
  year={2021}
}
```
