### ISSUE TITLE
Is there any way to use the Clip model in the Java technology stack?

### ISSUE THREAD

**Issue by zhangjh** [openai/CLIP#364]
As the title mentioned, Is there any ways to use clip in java or android?
Googled a long time, no useful infos searched...

**Comment by TheTensorDude** [comment]
Possible, you can convert the weights to tflite or onnx and integrate it in your java project. You can use quantization as well to reduce the size of the model.

**Comment by zhangjh** [comment]
Thanks for answering. Have used onnx already.
