### ISSUE TITLE
Feedback link in Model Card links to a private Google Form

### ISSUE THREAD

**Issue by Rijgersberg** [openai/CLIP#38]
Like the title says: the [Model Card](https://github.com/openai/CLIP/blob/main/model-card.md) features a feedback link at the bottom, but when I try to open the Google Form it says the form is private to the organization of the owner.

**Comment by jongwook** [comment]
Thanks for reporting this! We have just updated the form settings to not require a Google login. Please let us know if you still have the issue.

**Comment by Rijgersberg** [comment]
It works now! Thanks for the quick fix.
