### ISSUE TITLE
colab is broken ?

### ISSUE THREAD

**Issue by evanthebouncy** [openai/CLIP#4]
this cell:

tokenizer = SimpleTokenizer()
text_tokens = [tokenizer.encode("This is " + desc + "<|endoftext|>") for desc in texts]

when you run it, generates the following error:

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-16-ed0057d0ca54> in <module>()
----> 1 tokenizer = SimpleTokenizer()
      2 text_tokens = [tokenizer.encode("This is " + desc + "<|endoftext|>") for desc in texts]

NameError: name 'SimpleTokenizer' is not defined

**Comment by jongwook** [comment]
Hi, there is a hidden cell above that in the "text preprocessing" section. Could you check if that cell was executed?

**Comment by evanthebouncy** [comment]
sorry I must have missed that cell. this has been resolved. thanks !
