### ISSUE TITLE
How to only fine-tune the image encoder?

### ISSUE THREAD

**Issue by GA-17a** [openai/CLIP#403]
When I want to feed only the parameters of the image encoder (self.model.encode_image.parameters()) into the optimizer, it shows that "AttributeError: 'function' object has no attribute 'parameters'". It's ok for "self.model.parameters()".

Anyone knows how to solve this problem?

**Comment by Danny-1-8** [comment]
man,cause that's a function not A module,try with the "self.model.visual"

**Comment by GA-17a** [comment]
> man,cause that's a function not A module,try with the "self.model.visual"

It's been resolved in the same way, thank you.

**Comment by GA-17a** [comment]
> man,cause that's a function not A module,try with the "self.model.visual"
It has been solved in the same way, thank you.

**Comment by Dinosaurcubs** [comment]
> When I want to feed only the parameters of the image encoder (self.model.encode_image.parameters()) into the optimizer, it shows that "AttributeError: 'function' object has no attribute 'parameters'". It's ok for "self.model.parameters()".
> 
> Anyone knows how to solve this problem?

I met the same question,bro. Could u please help me about the solution you took
