### ISSUE TITLE
CLIp doesn't work with  Mac MPS

### ISSUE THREAD

**Issue by power9799** [openai/CLIP#406]
I tried to set device to MPS, but it doesn't work.
device = "cuda" if torch.cuda.is_available() else "MPS"
model, preprocess = clip.load("ViT-B/32", device=device)
RuntimeError: Expected one of cpu, cuda, ipu, xpu, mkldnn, opengl, opencl, ideep, hip, ve, fpga, ort, xla, lazy, vulkan, mps, meta, hpu, mtia, privateuseone device type at start of device string: MPS

**Comment by jimurk** [comment]
How did you solve this problem?

**Comment by Len02805** [comment]
There is no "CLIP.png" under your dir. Just put a PNG file to the path then the problem solved,

**Comment by Len02805** [comment]
There is no "CLIP.png" under your directory. Just put a PNG file to the path then the problem solved.
