### ISSUE TITLE
attention on the text

### ISSUE THREAD

**Issue by haofanwang** [openai/CLIP#47]
Given a sentence, is it possible to know which words receive more attention? In practice, I found that CLIP focused on several keywords in the sentence.

**Comment by jongwook** [comment]
See #18

**Comment by haofanwang** [comment]
Hi, @jongwook, I modified the code based on the suggestion, so I got the weight from the multihead-attention layer. But it is a tensor with shape (batch_size, target sequence length, source sequence length) = (1, 77, 77). How do I visualize this matrix to show the importance of each word?

**Comment by haofanwang** [comment]
solved.

**Comment by jongwook** [comment]
Glad to know that it sorted out! I haven't actually tried visualizing the attention map, and it's very intriguing to see. Thanks for making [a notebook](https://colab.research.google.com/github/haofanwang/natural-language-joint-query-search/blob/main/colab/clip_attention.ipynb) for this :D
