### ISSUE TITLE
Non-jit version of model?

### ISSUE THREAD

**Issue by jmhessel** [openai/CLIP#5]
Hi!

Thanks for the code release, and for the great work!! I was wondering if it might be possible to release a non-jit version of the model. This might make it easier to convert to other platforms, e.g., tensorflow. What do you think?

Jack

**Comment by jongwook** [comment]
Hello, thanks for your interest! We wanted to keep the release volume minimal and decided to release the JIT model only. 

That being said, I guess it'll be relatively straightforward to recover the Python code from the JIT model via `model.code`, `model.visual.code`, etc. (I wonder if there's an automated tool for this)

I also expect there will be implementations like [lucidrain's](https://github.com/lucidrains/DALLE-pytorch/blob/b794832f12bb6367d9b3ae4462a3d227e7560412/dalle_pytorch/dalle_pytorch.py#L151-L229) or others that will support importing the CLIP model weights.

**Comment by jmhessel** [comment]
Gotcha, that makes sense! It's definitely possible to get a non-JIT version using `model.code`, just a bit tedious :) Thanks!

**Comment by jongwook** [comment]
Hello! As written in #9 as well, we are preparing to release the model code this week, which will allow users to inspect and modify the architecture more conveniently.

**Comment by jongwook** [comment]
The model code is now available in [model.py](https://github.com/openai/CLIP/blob/main/model.py)
