### ISSUE TITLE
Multimodal projection matrix with ModifiedResNet

### ISSUE THREAD

**Issue by PaulLerner** [openai/CLIP#51]
Hi,

There's something unclear to me about the code:  
It's seems quite clear that the image is projected in the multimodal space [here](https://github.com/openai/CLIP/blob/main/clip/model.py#L233) with the VisualTransformer and that the text is projected [there](https://github.com/openai/CLIP/blob/main/clip/model.py#L349) but what about ModifiedResNet? It doesn't seem to project the visual features in the multimodal space, did I miss something?

Bests,

**Comment by jongwook** [comment]
It's not explicitly written as the other operations, but the projection matrix corresponding to the ResNet models is [here](https://github.com/openai/CLIP/blob/main/clip/model.py#L82-L83), within the self-attention pooling operation. This reduces the dimensionality from the resnet width to the embedding dimension.

**Comment by PaulLerner** [comment]
Oh ok, I thought there would be an extra layer after this, as in VisualTransformer, thanks !
