### ISSUE TITLE
tokenizer.encode vs tokenizer.encoder

### ISSUE THREAD

**Issue by normster** [openai/CLIP#56]
Hi,

I noticed that in the code and the colab notebooks you alternate between calling tokenizer.encode() and indexing into the tokenizer.encoder dict. What's the difference between the two? `tokenizer.encode('the')` returns `[518]` but `tokenizer.encoder['the']` returns `599`.

Thanks!

**Comment by crowsonkb** [comment]
If you look at the tokenizer.encoder dict, you can see that 599 is 'the' but 518 is 'the' followed by a word boundary. So `.encode('the p')` gives `[518, 335]` while `.encode('thep')` gives `[599, 335]`. It's probably correct to use the `encode()` method.
