### ISSUE TITLE
Image to text translation

### ISSUE THREAD

**Issue by KyloRen1** [openai/CLIP#59]
Hello, 

As I saw in other Issues it is possible to make a similar search for images https://github.com/openai/CLIP/issues/1#issue-779675076 and not possible to search for similar words without a given set of possible labels https://github.com/openai/CLIP/issues/27#issue-794492943 

So I have done the following:
1. Preprocessing of the following image
![apple](https://user-images.githubusercontent.com/35574157/110634934-3a2ba500-81b3-11eb-9a7d-1b7fb706f255.png)
2. iteration over each text embedding representations and computing cosine similarity with the input image

And I have obtained the following most similar tokens: amphibious topless innis enburg socialmediamarketing cumbwynonna canal titi forty stiff ldnont scarecrow chilly norwegian gophernadal strategically consolidation naver 

I wonder, is there a way we can caption the image using text embedding representations from CLIP for the most similar tokens?

**Comment by jongwook** [comment]
Hi, if I understood you correctly...

The token embedding space will not be directly comparable to the feature space. Those tokens are processed through transformer layers, and the information summarized at the EOT token is then [projected](https://github.com/openai/CLIP/blob/main/clip/model.py#L349) to the feature space. In fact, they don't even have to be the same dimensions, which is the case for the RN50 model.

The confusion might be coming from a transformer language model's case where the unembedding layer typically shares the weights with the token embeddings, so its output feature will somewhat correlate with the embeddings of probable next tokens.

If you just need a word, you could try calculating the text features corresponding to the common words in a dictionary. It might also be possible to fine-tune a language model using something like REINFORCE to optimize for high similarity with the image, but of course, YMMV.

**Comment by julienbelangerunity** [comment]
@jongwook So if I get this right, 

if I train something like:

`text→clip.encode_text(text)→embedding→decode(embedding)→text`

then do:

`image→clip.encode_image(image)→embedding→decode(embedding)→text`

**Using the same decoder both times**, casually assuming the two embedding spaces to be related and decodable using the same architecture.

Would this be doable if both encoders shared the same weights? 

If the two embeddings are not relatable how can we compute the similarity between the two?

**Thanks a lot!**
