### ISSUE TITLE
pip installable package

### ISSUE THREAD

**Issue by lucidrains** [openai/CLIP#60]
Hi and thanks for the great model :)

I was wondering if you would be open to publishing this to PyPI, as you have done for gym and dall_e. It would be convenient to be able to include this as a dependency in `setup.py` and for others to be able to use right away without an extra `pip install git+{repo}`

**Comment by nreimers** [comment]
Yes, a pip install would be nice.

As a work-around you can use SentenceTransformers, where CLIP is integrated:
```
pip install sentence-transformers
```

Then you can use CLIP like this:
```
from sentence_transformers import SentenceTransformer, util
from PIL import Image

#Load CLIP model
model = SentenceTransformer('clip-ViT-B-32')

#Encode an image:
img_emb = model.encode(Image.open('two_dogs_in_snow.jpg'))

#Encode text descriptions
text_emb = model.encode(['Two dogs in the snow', 'A cat on a table', 'A picture of London at night'])

#Compute cosine similarities 
cos_scores = util.cos_sim(img_emb, text_emb)
print(cos_scores)
```

More details
https://www.sbert.net/examples/applications/image-search/README.html#usage

**Comment by lucidrains** [comment]
@nreimers thanks for cuing me in Nils! unfortunately I need to be able to pass in an image tensor, so it is conductive to gradients to the origin

**Comment by jongwook** [comment]
Hi @lucidrains, while we may add some code/model updates or compatibility fixes going forward in this repo, we'd like to not make an additional commitment to provide semantic versioning / maintenance by pushing the packages to PyPI.

Meanwhile, the repo is MIT-licensed, and you're welcome to package the code yourself or include in your libraries. I see [some](https://www.reddit.com/r/Python/comments/l64709/open_source_library_for_openais_clip_to_create/) [users](https://pypi.org/project/clip-by-openai/) already did so.

**Comment by lucidrains** [comment]
Hi Jong! Yup, anything would be better than nothing :)
