### ISSUE TITLE
Non-jit version model archive

### ISSUE THREAD

**Issue by LucasWangZH** [openai/CLIP#67]
Hi,

do you have a non-jit version model archive. To get a non-jit version model by fetching state_dict from the current jit version model archive would encounter following problem:

D:\anaconda3\envs\torch171\python.exe D:/code/CLIP-main/main.py
Traceback (most recent call last):
  File "D:/code/CLIP-main/main.py", line 16, in <module>
    model = clip.load(name,device,jit=False)
  File "D:\code\CLIP-main\clip\clip.py", line 114, in load
    model = build_model(state_dict or model.state_dict()).to(device)
  File "D:\code\CLIP-main\clip\model.py", line 431, in build_model
    model.load_state_dict(state_dict)
  File "D:\anaconda3\envs\torch171\lib\site-packages\torch\nn\modules\module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CLIP:
	size mismatch for logit_scale: copying a param with shape torch.Size([]) from checkpoint, the shape in current model is torch.Size([1]).

**Comment by jongwook** [comment]
Hi, there was a temporary bug (#66) regarding this earlier today. Does it still happen with the latest commit https://github.com/openai/CLIP/commit/8a665a683d791ed3491fedadcb3c91878f9eb78d?

**Comment by LucasWangZH** [comment]
Great! The bug is gone with the latest commit.
