### ISSUE TITLE
Input size

### ISSUE THREAD

**Issue by qwertyforce** [openai/CLIP#69]
Is it possible to use this neural network with images larger than 224x224 without cropping/resizing?

**Comment by jongwook** [comment]
Not out-of-the-box, but you might want to try a 2-D interpolation technique similar to what [Vision Transformer (Section 3.2)](https://arxiv.org/pdf/2010.11929.pdf) did for fine-tuning on higher resolution. This is how we trained our largest model (ViT-L/14-336px).

**Comment by qwertyforce** [comment]
> Not out-of-the-box, but you might want to try the 2-D interpolation technique similar to what [Vision Transformer (Section 3.2)](https://arxiv.org/pdf/2010.11929.pdf) did for fine-tuning on higher resolution. This is how we trained our largest model (ViT-L/14-336px).

Thanks!
