### ISSUE TITLE
Doesn't work on PyTorch 1.8

### ISSUE THREAD

**Issue by interfect** [openai/CLIP#71]
PyTorch recently had a 1.8 release, bringing much better support for backing `torch.cuda` tensors with AMD GPUs.

However, CLIP hasn't been ported to PyTorch 1.8 yet.

In particular, CLIP still uses the deprecated and now removed `pytorch.irfft`, which needs to be replaced with calls to methods in the `torch.fft` namespace to work on PyTorch 1.8.

Unfortunately, [the PR that removed support for the old methods](https://github.com/pytorch/pytorch/pull/48594) doesn't provide a recipe for translating calls that can be executed by someone who doesn't understand the finer points of FFTs. It seems to me that the square-root-of-a-bunch-of-stuff normalization method of the old function isn't available as any of the normalization modes of `torch.fft.irfft`, and I'm not sure of the number of dimensions involved here, or whether we have the input versus the output sizes handy.

**Comment by interfect** [comment]
Sorry, this is on the wrong project.

**Comment by jongwook** [comment]
FWIW, CLIP doesn't work on 1.8 either. I'm keeping #49 open to track the compatibility fix.
