### ISSUE TITLE
How to predict one's age using CLIP?

### ISSUE THREAD

**Issue by MagicCodess** [openai/CLIP#74]
Thanks for the great work!
What's the most rational label when predict age, thx!

**Comment by nguyenhoan1988** [comment]
I have tried different way to use CLIP for age prediction.
So far using CLIP with precise age like "5 years old, 10 years old" did not work well.
I found using descriptive phrases about age works better, like: "very young human, or elderly, etc."

**Comment by MagicCodess** [comment]
> I have tried different way to use CLIP for age prediction.
> So far using CLIP with precise age like "5 years old, 10 years old" did not work well.
> I found using descriptive phrases about age works better, like: "very young human, or elderly, etc."

thanks~I will have a try~
