### ISSUE TITLE
Evaluation with Pascal VOC2007 classification

### ISSUE THREAD

**Issue by meigaoms** [openai/CLIP#75]
Hi there,
For this multi-label datasets, I used sklearn MultiOutputRegressor with estimator logisticRegression and tested it with several models. All scores I got are significantly higher than corresponding score in Table 10: ResNet50 89.1 (83.8 CLIP), ResNet101 88.7 (84.4 CLIP), Efficientnet_b0 88.6 (84.4 CLIP), CLIP_VIT_B32 89.2 (87.7 CLIP). 
I'm wondering if my evaluation logic for this multi-label dataset is different from yours, since MultiOutputRegressor trains 20 estimators under the hood. However, with a single logisticRegression model, it handles single label problem only.  Could you share more information of how you do linear probe with this multi-label dataset?

**Comment by Sierkinhane** [comment]
Hi, can you provide your evaluation code in computing accuracy score? @meigaoms Maybe I have some mistakes in calculating mAP score.
