### ISSUE TITLE
how to define RN50X64 config parameters?

### ISSUE THREAD

**Issue by QYinyourmind** [openai/CLIP#76]
I analysis the pretrained RN50X4 to obtain (4, 6, 10, 6) 80 , can you provide the RN50X64 config parameters?thanks

**Comment by jongwook** [comment]
You can find those hyperparameters listed in the last page of the [paper](https://arxiv.org/pdf/2103.00020.pdf):

![image](https://user-images.githubusercontent.com/266841/113978206-82f96c80-97f8-11eb-9e73-6544e63062d4.png)
