### ISSUE TITLE
ImageNet text prompts

### ISSUE THREAD

**Issue by MartinPernus** [openai/CLIP#80]
Hi,

I was wondering where I could find the text prompts, used for ImageNet classification task.

**Comment by jongwook** [comment]
See [notebooks/Prompt_Engineering_for_ImageNet.ipynb](https://github.com/openai/CLIP/blob/main/notebooks/Prompt_Engineering_for_ImageNet.ipynb). You can also open this notebook in [Colab](https://colab.research.google.com/github/openai/clip/blob/master/notebooks/Prompt_Engineering_for_ImageNet.ipynb).

**Comment by MartinPernus** [comment]
Thank you.
