### ISSUE TITLE
Attention map to extract objects

### ISSUE THREAD

**Issue by rodrigoheck** [openai/CLIP#82]
I have no idea if something like this is possible, but if I have, for example, an image of a supermarket shelve and the text "juice", could I in theory use the attention map to extract all the regions in which the model found something similar to a juice?

**Comment by jongwook** [comment]
It's not as straightforward as CLIP doesn't have cross-modal attentions and the only cross-modal interaction is the final dot product, but you could start with cropping the images into square-shaped patches and finding the cosine similarity between the image features of those patches and the query text features.

**Comment by rodrigoheck** [comment]
Thanks @jongwook, I will try this approach. By the way, will CLIP be compatible with DeiT from Facebook? Considering how inference is considerably quicker, this would fit perfectly into my pipeline.

**Comment by ModMorph** [comment]
FYI: @rodrigoheck  you might be interested in the following projects: https://ganpaint.io/miniclip/ and https://github.com/hila-chefer/Transformer-MM-Explainability - these have saliency and/or gradcam maps for RN50 and ViTB CLIP respectively. (Although I think the Transformer method is new so not sure how confident to be in it.)

**Comment by g-luo** [comment]
@ModMorph Do you have insight on which layers are best to use as the saliency layer for Grad CAM (for the visual transformer ViT models)? For the resnet the miniclip demo uses the relu from the last visual layer, and I'm wondering what's the best for the visual transformer.

**Comment by ModMorph** [comment]
Hi @g-luo, good timing. I may be circling back to this...but I haven't had time to
look at how Transformer-MM-Explainability's technique works yet, just that in trying
their demos, it seemed to look reasonably well. 

One thing I noticed you might be interested in, is that there's seems to be some
more attention head related information you can derive by taking the full
x[:,:,:] instead of the x[:,0,:] in the last lines of the VisualTransformer forward method. I thought maybe it was de facto a vector describing
each of the 49 32x32x3 pixel patches w.r.t. to the embedding vector..but
I'm new to transformers. When I subtracted the 49 vectors from the embedding 
vector currently being used, I got what seemed like a coherent heatmap description
of some basic scenes I tried. HTH. (Not exactly same as the level of detail you want,
I'm still experimenting whether I can make any use out of it.) 

![image](https://user-images.githubusercontent.com/7545237/115787284-2c0aa000-a37f-11eb-9005-2c396ed33705.png)

**Comment by jihwanp** [comment]
> Hi @g-luo, good timing. I may be circling back to this...but I haven't had time to look at how Transformer-MM-Explainability's technique works yet, just that in trying their demos, it seemed to look reasonably well.
> 
> One thing I noticed you might be interested in, is that there's seems to be some more attention head related information you can derive by taking the full x[:,:,:] instead of the x[:,0,:] in the last lines of the VisualTransformer forward method. I thought maybe it was de facto a vector describing each of the 49 32x32x3 pixel patches w.r.t. to the embedding vector..but I'm new to transformers. When I subtracted the 49 vectors from the embedding vector currently being used, I got what seemed like a coherent heatmap description of some basic scenes I tried. HTH. (Not exactly same as the level of detail you want, I'm still experimenting whether I can make any use out of it.)
> 
> ![image](https://user-images.githubusercontent.com/7545237/115787284-2c0aa000-a37f-11eb-9005-2c396ed33705.png)

Did that similarity map just measure the similarity between local feature and text(apple)? I tried similar things, but the local similarity of the text-related parts was rather low.

**Comment by gordinmitya** [comment]
now there's such a thing https://huggingface.co/blog/clipseg-zero-shot

**Comment by chinmay5** [comment]
Here is a very simple code snippet in case someone finds it useful.

```
def generate_crop_dict(img, preprocess):
    # Convert image into 56 by 56 crops
    offset = 56
    image_crop_dict = {}
    for h in range(0, 224, offset):
        for w in range(0, 224, offset):
            area = (w, h, w + offset, h + offset)
            crop = img.crop(area)
            crop = crop.resize((224, 224), Image.ANTIALIAS)
            # Include the batch dimension
            image_crop_dict[area] = torch.tensor(preprocess(crop)).unsqueeze(0)
    return image_crop_dict


def highlight_area(img, region, factor, outline_color=None, outline_width=1):
    """ Highlight specified rectangular region of image by `factor` with an
        optional colored  boarder drawn around its edges and return the result.
    """
    img = img.copy()  # Avoid changing original image.
    img_crop = img.crop(region)

    brightner = ImageEnhance.Brightness(img_crop)
    img_crop = brightner.enhance(factor)
    img.paste(img_crop, region)
    # Optionally draw a colored outline around the edge of the rectangular region.
    if outline_color:
        draw = ImageDraw.Draw(img)  # Create a drawing context.
        left, upper, right, lower = region  # Get bounds.
        coords = [(left, upper), (right, upper), (right, lower), (left, lower),
                  (left, upper)]
        draw.line(coords, fill=outline_color, width=outline_width)
    return img


def viz_pseudo_attn_maps(model, img, text, preprocess):
    image_dict = generate_crop_dict(img, preprocess)
    sim_dict = {}
    for crop_loc, image in image_dict.items():
        with torch.no_grad():
            image_features = model.encode_image(image).float()
            text_features = model.encode_text(text).float()
            image_features /= image_features.norm(dim=-1, keepdim=True)
            text_features /= text_features.norm(dim=-1, keepdim=True)
            similarity = text_features.cpu().numpy() @ image_features.cpu().numpy().T
            sim_dict[crop_loc] = similarity.item()
    bbox = max(sim_dict, key=sim_dict.get)
    print(f"Max patch is {max(sim_dict, key=sim_dict.get)}")
    # We pass the original image and the rectangle.
    red = ImageColor.getrgb('red')
    img2 = highlight_area(img, bbox, 2.5, outline_color=red, outline_width=2)
    plt.imshow(img2)
    plt.show()
```
