### ISSUE TITLE
Share prompts for other zeroshot eval datasets?

### ISSUE THREAD

**Issue by ytsheng** [openai/CLIP#87]
Thank you for providing the prompt engineering file for the ImageNet [here](https://github.com/openai/CLIP/blob/main/notebooks/Prompt_Engineering_for_ImageNet.ipynb)

I am curious if you are willing to share the prompts for one other datasets used for the Zeroshot Eval results shown in the paper? I was able to reproduce the ImageNet zero shot eval results but unable to reproduce other results. The zeroshot eval top1 accuracy is 3 to 8 percentages off for the Food101 dataset (show below). This is with the prompt suggested by the paper: "a photo of a {}, a type of food." Curious if you are using an ensemble of prompts to report the results? If so, could you share the ensemble of prompts for one of those datasets?  

```
ours / reported in paper
ViT/B-32: 81.4812  / 84.4 
ResNet50: 73.0099 / 81.1
ResNet101: 75.9644 / 83.9
ResNet50x4: 80.4753 / 86.8
```

**Comment by jongwook** [comment]
The prompts can now be found at https://github.com/openai/CLIP/blob/main/data/prompts.md
