### ISSUE TITLE
CUDA out of memory when running the training code on ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by lycutter** [openai/CLIP#88]
When I re-train the clip network on Windows, it works well. But I re-train it on unbuntu, it always  reminds me of CUDA out of memory no matter how I set the batch size. The configuration information of Windows and ubuntu are showed as follows:
Windows:
1. the type of graphic card：GTX950M
2. pytorch version: 1.7.1
3. cuda version: 10.2

Ubuntu:
1. the type of graphic card: RTX2080
2. pytorch version: 1.7.1
3. cuda version: 10.1

Besides, other pytorch projects work well on the Ubuntu. So I think the graphic card also works well and the memory is also sufficient. I try to update the pytorch version to 1.8, but it seems that it only support the version 1.7.1.

**Comment by vinson2233** [comment]
Can you share your training code? 
Have you look the CUDA memory when loading the data, loading the model and doing a single forward?

**Comment by lycutter** [comment]
> Can you share your training code?
> Have you look the CUDA memory when loading the data, loading the model and doing a single forward?

Hello, my training code can be available at https://github.com/lycutter/CLIP/tree/master. 
When I ran forward step on ubuntu, the allocated memory of graphic card didn't change.

**Comment by dragen1860** [comment]
@lycutter Hi, do you have multiple GPUs on ubuntu. YOu may need to block other GPUs in case of full GPU used.

**Comment by jongwook** [comment]
Try memory profiling using [pytorch_memlab](https://github.com/Stonesjtu/pytorch_memlab) to identify which operation causes the highest memory jump, and since you have the Windows version working, comparing the profiling results on Windows vs Linux would help. [Setting environment variable `CUDA_LAUNCH_BLOCKING=1`](https://pytorch.org/docs/stable/notes/cuda.html#asynchronous-execution) will also help getting more accurate profiling.

**Comment by lycutter** [comment]
> Try memory profiling using [pytorch_memlab](https://github.com/Stonesjtu/pytorch_memlab) to identify which operation causes the highest memory jump, and since you have the Windows version working, comparing the profiling results on Windows vs Linux would help. [Setting environment variable `CUDA_LAUNCH_BLOCKING=1`](https://pytorch.org/docs/stable/notes/cuda.html#asynchronous-execution) will also help getting more accurate profiling.

It works, thanks you!
