### ISSUE TITLE
This model can support fine tuning？

### ISSUE THREAD

**Issue by lonngxiang** [openai/CLIP#89]

**Comment by vinson2233** [comment]
What do you mean?
Do you want to train it for your dataset? check this https://github.com/openai/CLIP/issues/83

**Comment by lonngxiang** [comment]
> What do you mean?
> Do you want to train it for your dataset? check this #83
yes, just like that

**Comment by lonngxiang** [comment]
> What do you mean?
> Do you want to train it for your dataset? check this #83

tks
