### ISSUE TITLE
Half precision error on forward pass of RN50 and RN101 models

### ISSUE THREAD

**Issue by spetryk** [openai/CLIP#92]
Hi, thanks for putting together a great repo. It has worked smoothly, except for the following:

When running the line `logits_per_image, logits_per_text = model(image, text)` with the RN50 or RN101 models, I run into the following error:

```
RuntimeError: default_program(57): error: identifier "prim_constantchunk_flat__1" is undefined

default_program(58): error: no operator "=" matches these operands
            operand types are: half = float

2 errors detected in the compilation of "default_program".

nvrtc compilation failed: 
```
And then there's a bunch of C-looking code from the error message that I can post if needed.

A sample of the code I ran, for reference (though it's pretty much straight from the example):
```
with torch.no_grad():
    text = clip.tokenize(text_list).to(device)
    for i in tqdm(range(len(images))):
        image = preprocess(Image.open(images[i])).unsqueeze(0).to(device)    
        logits_per_image, logits_per_text = model(image, text)
```

It seems sort of indeterministic - in a for loop, sometimes it runs for one pass and breaks on the second. Sometimes it breaks on the first.

I'm using one GPU. The `text` is dtype `torch.int64`, and `image` is dtype `torch.float32`.

However, the forward pass works with the RN50x4 and ViT-B/32 models.

There are a couple other issues at the moment that address half-precision:
- #57, on mix-precision training
- #30, on the half-precision for a GPU and full for a CPU

Yet, these don't mention problem I'm running into.

Any help would be really appreciated!

**Comment by jongwook** [comment]
Can you try supplying `jit=False` while loading the model? I'm thinking of making jit=False the default since it's less compatible across PyTorch versions. (cf. #79)

**Comment by spetryk** [comment]
Great, that seems to have been the problem! It's working now. Thanks! :tada:

**Comment by ooza** [comment]
@spetryk 
Hi, as a new in the domain of image captioning, I'm wondering if the text_list was prepared by yourself or it's a default setting?
What should I prepare if I want to test the available clip models on my own images ?
Thanks
