### ISSUE TITLE
Inconsistent naming

### ISSUE THREAD

**Issue by haofanwang** [openai/CLIP#94]
In the paper, you mentioned that ViT meant "Vision Transformer". But in the code, the name of visual encoder is [VisualTransformer](https://github.com/openai/CLIP/blob/cfcffb90e69f37bf2ff1e988237a0fbe41f33c04/clip/model.py#L202). Is this a typo?

**Comment by jongwook** [comment]
Yes, it should've been named `VisionTransformer` for consistency.
